name: 🕷️ Run Wiraa Crawler

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  crawl:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          playwright install --with-deps

      - name: Debug environment
        run: |
          echo "SUPABASE_URL=[$SUPABASE_URL]"
          echo "SUPABASE_SERVICE_ROLE_KEY=[$SUPABASE_SERVICE_ROLE_KEY]"
          echo "OPENROUTER_API_URL=[$OPENROUTER_API_URL]"
          echo "OPENROUTER_API_KEY=[$OPENROUTER_API_KEY]"

      - name: Run crawler
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
          OPENROUTER_API_URL: ${{ secrets.OPENROUTER_API_URL }}
          OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
        run: |
          python crawler.py
