# .github/workflows/ingest-telegram.yml
name: 🛰️ Ingest Supplier Telegram

on:
  schedule:
    - cron: '0 * * * *'    # at minute 0 of every hour
  workflow_dispatch:      # manual trigger too

jobs:
  ingest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install python-telegram-bot supabase crawl4ai beautifulsoup4 torob-integration

      - name: Run Telegram ingest
        env:
          TELEGRAM_BOT_TOKEN:      ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TG_CHANNEL_ID:           ${{ secrets.TG_CHANNEL_ID }}
          SUPABASE_URL:            ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
        run: |
          python supplier_ingest/ingest.py
