name: 🤖 Match Supplier Offers

on:
  schedule:
    - cron: '5 * * * *'   # every hour at :05
  workflow_dispatch:

jobs:
  match:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with: python-version: '3.11'
      - run: |
          cd supplier_ingest
          pip install rapidfuzz supabase
      - run: python matcher.py
        env:
          SUPABASE_URL:              ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
