name: 🤖 Match Supplier Offers

on:
  schedule:
    - cron: '5 * * * *'   # 5 minutes past the hour, after ingest
  workflow_dispatch:

jobs:
  match:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          cd supplier_ingest
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run matcher
        env:
          SUPABASE_URL:             ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE_KEY:  ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
        run: |
          python supplier_ingest/matcher.py
